### ISSUE TITLE
Provide docs for configuring LEC to work with Elastic Clod

### ISSUE THREAD

**Issue by acesdm** [strongdm/log-export-container#106]
**Is your feature request related to a problem? Please describe.**
Our ES output in the LEC does not support writing to a secure ES cluster.

**Describe the solution you'd like**
Allow for ES user/ pass so that the LEC can write to a secure ES cluster.

**Describe alternatives you've considered**
Use unsecured ES.  I am not sure this would be palatable for enterprises.

**Additional context**

**Comment by camposer** [comment]
We're trying to not make any assumptions for the different outputs
