### ISSUE TITLE
Some websites aren't handled properly

### ISSUE THREAD

**Issue by mdube667** [strongdm/log-export-container#34]
**Describe the bug**

Olive, using log-exporter, is seeing some errors from website resources:

`pattern not matched message="{\"type\":\"start\",\"timestamp\":\"2021-11-04T01:03:02.91304704Z\",\"uuid\":\"020Qriqc5K4qql5nreZsIq8j2OVA\",\"datasourceId\":\"rs-xxxx\",\"datasourceName\":\"olive-kg-kibana/snd\",\"userId\":\"a-xxx\",\"userName\":\"user name\",\"query\":\"GET /_plugin/kibana/plugins/kibanaOverview/assets/kibana_discover_light.svg HTTP/1.1\\r\\nHost: olive-kg-neptune-snd.olive.sdm.network\\r\\nAccept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8\\r\\nAccept-Encoding: gzip, deflate, br\\r\\nAccept-Language: en-US,en;q=0.9\\r\\nConnection: keep-alive\\r\\nReferer: https://olive-kg-neptune-snd.olive.sdm.network/_plugin/kibana/app/kibana_overview\\r\\nSec-Fetch-Dest: image\\r\\nSec-Fetch-Mode: no-cors\\r\\nSec-Fetch-Site: same-origin\\r\\nSec-Gpc: 1\\r\\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36\\r\\n\\r\\n\",\"hash\":\"e75259400255f0de66d6bb421a9ba57d0c318c60\"}"
`

**To Reproduce**
I'm not exactly sure what specifically causes the problem but it looks like it's a kibana website. Doesn't seem to happen with all websites.

**Expected behavior**
The log entry should be handled like others.

**Comment by camposer** [comment]
This problem is related to the [parse_sdm](https://github.com/strongdm/log-export-container/blob/main/fluentd/plugins/parser_sdm_json.rb)
