### ISSUE TITLE
Extract ssh/rdp/k8s info

### ISSUE THREAD

**Issue by wallrony** [strongdm/log-export-container#37]
**Is your feature request related to a problem? Please describe.**
To extract ssh log files from SDM, we need to use sdm-cli commands to make the conversion and output, and this is a very manual process.

**Describe the solution you'd like**
There's already a script to automate this in [contrib logging section](https://github.com/strongdm/contrib/tree/main/logging) and it would be nice to have this script as a plugin in Log Export Container directly.

**Comment by camposer** [comment]
In order to enable this, you need to pass the following variable: `LOG_EXPORT_CONTAINER_DECODE_CHUNK_EVENTS`
