### ISSUE TITLE
Support audit activity logs

### ISSUE THREAD

**Issue by wallrony** [strongdm/log-export-container#47]
**Is your feature request related to a problem? Please describe.**
Currently, all logs that are sent to Log Export Container are related to SDM Resources, but, there are some logs like Activities (that comes from SDM Audit) that would be great to see in LEC as well.

**Describe the solution you'd like**
Add an input plugin to execute, periodically, following the script from [StrongDM S3 Docs](https://www.strongdm.com/docs/installation/configure-logging/aws-s3), every 15 minutes, to send to LEC the SDM Audit Activity logs.

**Additional context**
It would be great to store the activity logs in a mongo instance like the last implementation about storing the common logs in Mongo (#45).

**Comment by camposer** [comment]
Added the new variable: LOG_EXPORT_CONTAINER_EXTRACT_AUDIT_ACTIVITIES

See docs.
