### ISSUE TITLE
Loki support through LEC

### ISSUE THREAD

**Issue by Crystalirlandez** [strongdm/log-export-container#59]
**Is your feature request related to a problem? Please describe.**
Customer - Wasabi uses Granfana and would like to use Loki for logging

**Describe the solution you'd like**
Ability to connect to Loki for logging

**Describe alternatives you've considered**
They currently use Elastic but they are sunsetting it and moving forward with Loki

**Additional context**

**Comment by tonylokko** [comment]
i've been doing some work on this.
https://grafana.com/docs/loki/latest/clients/fluentd/

shows we can add the fluent-plugin-grafana-loki to the gem file it then needs the loki_url as an environment variable

The main issue is the labels and classification

**Comment by Crystalirlandez** [comment]
Thank you for the update, @tonylokko. Please let me know if you need any more information, I think my customer would be willing to meet to share anything else you may need.
