### ISSUE TITLE
s3 log file format to json for rendering

### ISSUE THREAD

**Issue by mdube667** [strongdm/log-export-container#65]
**Is your feature request related to a problem? Please describe.**
Currently, the file format with s3 as output is like this:

`2022-02-10T20:35:47+00:00	class.start	{"type":"start","timestamp":"2022-02-10T20:35:46.895157772Z","uuid":"r24vyQoMZifkKy5bcRQBTSyYpScm","datasourceId":"rs-288662046205321d","datasourceName":"windowsies","userId":"a-0c68f84e602a86a1","userName":"Matt Dube","query":"{\"version\":1,\"width\":0,\"height\":0,\"duration\":5.23053397,\"command\":null,\"title\":null,\"env\":{},\"type\":\"rdp-basic\",\"fileName\":null,\"fileSize\":0,\"stdout\":null,\"lastChunkId\":0,\"clientCommand\":null,\"pod\":null,\"container\":null,\"requestMethod\":\"\",\"requestURI\":\"\",\"requestBody\":null}\n","hash":"70efea267d1b2e55120dfb12ca8267e1123c6444","sourceAddress":"35.81.212.119","sourceHostname":"ec2-35-81-212-119.us-west-2.compute.amazonaws.com"}
2022-02-10T20:35:56+00:00	class.chunk	{"type":"chunk","timestamp":`

I need to extract the json part to pass onto my rdp renderer. 

**Describe the solution you'd like**
Would it be possible to have the json part only logged as well? 

**Describe alternatives you've considered**
I've tried awk'ing the output and taking the 3rd field only but it doesn't catch all format, specially with the binary data in the chunks

**Comment by camposer** [comment]
Hi Matt, 

Just remove invalid log lines and assign to the resulting file a valid "relay log filename":
```
gzcat * | grep -v "fluent.warn" | awk -F'\t' '{ print $3 }' > all.log
mv all.log relay.1635171848.0.log
docker run --rm -ti -v ~/sdm/tmp/matt:/logs quay.io/sdmrepo/rdpreplay:latest --format 'json' r24vyQoMZifkKy5bcRQBTSyYpScm
```
