### ISSUE TITLE
LEC- pull logs instead of receiving logs

### ISSUE THREAD

**Issue by acesdm** [strongdm/log-export-container#66]
**Is your feature request related to a problem? Please describe.**
Customers fear the LEC going unavailable as that prevents the GW from functioning.

**Describe the solution you'd like**
Have fluentd pull local logs from gateways.  This may be tricky because it requires access to gateways/ relays.

**Describe alternatives you've considered**
accepting logs from gateways/ relays.  Having a cluster of LECs so a single LEC wouldn't be a single point of failure.

**Additional context**
This could also have the benefit of pulling sdm.log files from the gw/ relays.

**Comment by camposer** [comment]
We might need to implement something like this (see second use case):
![image](https://user-images.githubusercontent.com/313803/155001698-96de19a8-fe62-4ab6-841d-48ef1596c0f3.png)

**Comment by camposer** [comment]
As a first approach, we'll implement the file input using docker. The interface would look something like:
```
docker run -d -v ~ubuntu/.sdm/logs:/var/logs/sdm -e OUTPUT=s3 -e ... log-export-container
```
