### ISSUE TITLE
Add support for Devo 

### ISSUE THREAD

**Issue by samueljones2212** [strongdm/log-export-container#80]
Please add support for Devo for Log Export Container 

https://rubygems.org/gems/fluent-plugin-devo/versions/1.0.0

**Comment by camposer** [comment]
This is the repo: https://github.com/DevoInc/fluent-plugin-devo

In order to get a trial, we'd need to request access here: https://www.devo.com/demo/

**Comment by devlucassantos** [comment]
To add support to Devo we need to request access to a demo of the platform and we are waiting to schedule this demo to add this support to the LEC.

**Comment by camposer** [comment]
@samueljones2212 Devo didn't come back to us during yet. I guess we could move forward if the customer gives us access "somehow" to their account or they ask Devo to create a testing account for us. Could you please reach out to him and validate next steps?
